---
# Stat the named.conf and IPA default.conf file, if the file exists, then IPA is already configured.
- name: stat IPA configuration
  stat: path=/etc/ipa/default.conf
  register: ipa_stat

# FreeIPA Installation
- name: adding epel repo
  package: name={{item}} state=installed
  with_items:
    - epel-release

- name: adding required freeipa packages
  package: name={{item}} state=installed
  with_items:
    - bind
    - bind-utils
    - ipa-server
    - ipa-server-dns

- name: configuring firewall services
  firewalld: service={{item}} permanent=true state=enabled
  with_items:
    - http
    - https
    - ldap
    - ldaps
    - kerberos

- name: configuring firewall UDP ports
  firewalld: port={{item}} permanent=true state=enabled
  with_items:
    - 88/udp
    - 464/udp
    - 123/udp

- name: reload the firewall
  command: firewall-cmd --reload

- name: installing freeipa
  command: ipa-server-install --unattended --realm={{domain}} --ds-password={{dsmgr_password}} --admin-password={{admin_password}} --setup-dns --forwarder=8.8.8.8 --forwarder=8.8.4.4
  when: ipa_stat.stat.exists == False

# - name: Setting default IPA shell to bash
#   command: ipa config-mod --defaultshell=/bin/bash                                                                                   

