---
# Stat the named.conf and IPA default.conf file, if the file exists, then IPA is already configured.
- name: stat IPA configuration
  stat: path=/etc/ipa/default.conf
  register: ipa_stat

# Check to see if firewalld is installed
- name: grab list of installed packages
  package_facts:
    manager: auto

# FreeIPA Installation
# Commenting out package as iteration through items is slow, and yum is faster.
# - name: adding epel repo
#   package: name={{ item }} state=installed
#   with_items:
#     - epel-release

- name: adding epel repo
  yum:
    name:
      - epel-release
    state: present

# Commenting out package as iteration through items is slow, and yum is faster.
# - name: adding required freeipa packages
#   package: name={{ item }} state=installed
#   with_items:
#     - bind
#     - bind-utils
#     - ipa-server
#     - ipa-server-dns

- name: adding required freeipa packages
  yum:
    name:
      - bind
      - bind-utils
      - ipa-server
      - ipa-server-dns
    state: present

- name: stop service firewalld
  systemd:
    name: firewalld
    state: stopped
  when: '"firewalld" in ansible_facts.packages'
  failed_when: no
  changed_when: no

- name: configuring firewall services
  firewalld: service={{ item }} permanent=true state=enabled
  with_items:
    - http
    - https
    - ldap
    - ldaps
    - kerberos
  when: '"firewalld" in ansible_facts.packages'

- name: configuring firewall UDP ports
  firewalld: port={{ item }} permanent=true state=enabled
  with_items:
    - 88/udp
    - 464/udp
    - 123/udp
  when: '"firewalld" in ansible_facts.packages'

- name: start service firewalld
  systemd:
    name: firewalld
    state: started
  when: '"firewalld" in ansible_facts.packages'

- name: installing freeipa
  command: |
    ipa-server-install \
    --unattended \
    --realm={{ domain }} \
    --ds-password={{ dsmgr_password }} \
    --admin-password={{ admin_password }} \
    --setup-dns \
    --forwarder=8.8.8.8 \
    --forwarder=8.8.4.4
  when: not ipa_stat.stat.exists
