---
# We do this in 2 different calls to avert bind notify restarts from failing after freeipa is installed.
- hosts: ds-servers
  become: true
  roles:
    - clusterfrak.bind

- hosts: ds-servers
  become: true
  roles:
    - clusterfrak.freeipa
